var enemy_def: Array[Dictionary] = [
    {
        "id": "0",
        "name": "a",
        "health": 100,
        "damage": 40,
        "attack_range": 50,
        "attack_frame_min": 3,
        "attack_frame_max": 8,
        "attack_frame_count": 10,
        "movement_speed": 350,
        "offset_radius": 30,
        "enable_blood": true,
        "enable_hand": false,
        "use_default_attack_system": true,
    },
    {
        "id": "1",
        "name": "b",
        "health": 120,
        "damage": 45,
        "attack_range": 55,
        "attack_frame_min": 3,
        "attack_frame_max": 10,
        "attack_frame_count": 14,
        "movement_speed": 400,
        "offset_radius": 40,
        "enable_blood": true,
        "enable_hand": true,
        "use_default_attack_system": true,
    },
]
