var enemy_def: Array[Dictionary] = [
    {
        "id": "0",
        "name": "a",
        "health": 120,
        "damage": 40,
        "attack_range": 50,
        "attack_frame_min": 2,
        "attack_frame_max": 7,
        "attack_frame_count": 10,
        "movement_speed": 350,
        "offset_radius": 35,
        "enable_blood": true,
        "enable_hand": false,
        "use_default_attack_system": true,
    },
    {
        "id": "1",
        "name": "b",
        "health": 160,
        "damage": 45,
        "attack_range": 55,
        "attack_frame_min": 2,
        "attack_frame_max": 9,
        "attack_frame_count": 14,
        "movement_speed": 400,
        "offset_radius": 40,
        "enable_blood": true,
        "enable_hand": true,
        "use_default_attack_system": true,
    },
    {
        "id": "2",
        "name": "c",
        "health": 200,
        "damage": 25,
        "attack_range": 50,
        "attack_frame_min": 2,
        "attack_frame_max": 7,
        "attack_frame_count": 10,
        "movement_speed": 400,
        "offset_radius": 35,
        "enable_blood": true,
        "enable_hand": false,
        "use_default_attack_system": true,
    },
    {
        "id": "3",
        "name": "d",
        "health":1000,
        "damage": 75,
        "attack_range": 100,
        "attack_frame_min": 8,
        "attack_frame_max": 11,
        "attack_frame_count": 11,
        "movement_speed": 280,
        "offset_radius": 67,
        "enable_blood": true,
        "enable_hand": false,
        "use_default_attack_system": true,
    },
    {
        "id": "4",
        "name": "e",
        "health":800,
        "damage": 65,
        "attack_range": 95,
        "attack_frame_min": 2,
        "attack_frame_max": 11,
        "attack_frame_count": 12,
        "movement_speed": 290,
        "offset_radius": 98,
        "enable_blood": false,
        "enable_hand": false,
        "use_default_attack_system": true,
    },
]
