var sword_def: Array[Dictionary] = [
	{
		"id": "0",
		"name": "basic_sword",
		"pname": "Basic Sword",
		"bonus_damage": 20,
		"texture": "res://assets/sword1.png",
		"weight": 0.7,
	},
	{
		"id": "1",
		"name": "flamming_sword",
		"pname": "Flamming Sword",
		"bonus_damage": 30,
		"texture": "res://assets/sword3.png",
		"weight": 0.2,
	},
	{
		"id": "2",
		"name": "spear",
		"pname": "Spear",
		"bonus_damage": 35,
		"texture": "res://assets/spear.png",
		"weight": 0.1,
	},
	{
		"id": "3",
		"name": "ruby_sword",
		"pname": "Ruby Sword",
		"bonus_damage": 45,
		"texture": "res://assets/sword2.png",
		"weight": 0.5,
	},
	{
		"id": "4",
		"name": "red_great_sword",
		"pname": "Red Great Sword",
		"bonus_damage": 60,
		"texture": "res://assets/sword6.png",
		"weight": 0.1,
	},
]
